### PR TITLE
Trigger [ci] Test & Build on all pushes

### PR DESCRIPTION
**Pull request by EeroPaukkonen**
Previously we were not running Test and build in many cases where we should run it.
No issue running this on all pushes (other than a bit more run time in average)?

### CODE REVIEW

**Comment by thor** [comment]
I sort of question why we don't instead exclude files rather than have a whitelist 🤔 It seems like we're more likely to mess it up than the alternative

**Comment by EeroPaukkonen** [comment]
> I sort of question why we don't instead exclude files rather than have a whitelist 🤔 It seems like we're more likely to mess it up than the alternative

Hmm. Yea should not be any issues with `.github/workflows/release.yml`. I think. This will push a new image and create a new release but that should not be an issue.

**Review by thor — APPROVED** [review]
👍 for merging.

**Comment by thor** [comment]
I'll merge it into my branch.

**Comment by thor** [comment]
@EeroPaukkonen oooor not 😅

**Comment by EeroPaukkonen** [comment]
> @EeroPaukkonen oooor not 😅

Now you can merge from main. Even better.

**Pull request merged**
